/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Video = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'views' : IDL.Nat,
  'description' : IDL.Text,
  'likes' : IDL.Nat,
  'category' : IDL.Text,
  'dislikes' : IDL.Nat,
  'videoUrl' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Channel = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'subscriberCount' : IDL.Nat,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'author' : IDL.Text,
  'videoId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'addVideo' : IDL.Func([Video], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteVideo' : IDL.Func([IDL.Nat], [], []),
  'dislikeVideo' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannel' : IDL.Func([], [Channel], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], ['query']),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'incrementViews' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeVideo' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
  'subscribe' : IDL.Func([], [], []),
  'updateChannel' : IDL.Func([Channel], [], []),
  'updateVideo' : IDL.Func([IDL.Nat, Video], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'views' : IDL.Nat,
    'description' : IDL.Text,
    'likes' : IDL.Nat,
    'category' : IDL.Text,
    'dislikes' : IDL.Nat,
    'videoUrl' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Channel = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'subscriberCount' : IDL.Nat,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'author' : IDL.Text,
    'videoId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'addVideo' : IDL.Func([Video], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteVideo' : IDL.Func([IDL.Nat], [], []),
    'dislikeVideo' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannel' : IDL.Func([], [Channel], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], ['query']),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getVideosByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'incrementViews' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeVideo' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchVideos' : IDL.Func([IDL.Text], [IDL.Vec(Video)], ['query']),
    'subscribe' : IDL.Func([], [], []),
    'updateChannel' : IDL.Func([Channel], [], []),
    'updateVideo' : IDL.Func([IDL.Nat, Video], [], []),
  });
};

export const init = ({ IDL }) => { return []; };