/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Channel {
  'name' : string,
  'description' : string,
  'subscriberCount' : bigint,
}
export interface Comment {
  'id' : bigint,
  'body' : string,
  'createdAt' : bigint,
  'author' : string,
  'videoId' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : bigint,
  'title' : string,
  'duration' : string,
  'thumbnailUrl' : string,
  'views' : bigint,
  'description' : string,
  'likes' : bigint,
  'category' : string,
  'dislikes' : bigint,
  'videoUrl' : string,
  'uploadedAt' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, string], undefined>,
  'addVideo' : ActorMethod<[Video], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteVideo' : ActorMethod<[bigint], undefined>,
  'dislikeVideo' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannel' : ActorMethod<[], Channel>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[bigint], [] | [Video]>,
  'getVideos' : ActorMethod<[], Array<Video>>,
  'getVideosByCategory' : ActorMethod<[string], Array<Video>>,
  'incrementViews' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeVideo' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchVideos' : ActorMethod<[string], Array<Video>>,
  'subscribe' : ActorMethod<[], undefined>,
  'updateChannel' : ActorMethod<[Channel], undefined>,
  'updateVideo' : ActorMethod<[bigint, Video], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];